<?php

namespace App\Models;

use App\Models\Concerns\HasUuidPrimaryKey;
use Illuminate\Database\Eloquent\Model;

/**
 * FR-6.7 .. FR-6.10. One per contract version. risk_band is generated by the
 * database from risk_score — never written.
 */
class ContractAnalysis extends Model
{
    use HasUuidPrimaryKey;

    const UPDATED_AT = null;

    protected $table = 'contract_analyses';

    protected $keyType = 'string';

    public $incrementing = false;

    protected $fillable = [
        'id', 'tenant_id', 'contract_id', 'contract_version_id', 'ai_job_id', 'risk_score',
        'summary_ar', 'summary_en', 'coverage', 'confidence', 'risk_rubric_version',
    ];

    protected function casts(): array
    {
        return [
            'risk_score' => 'integer',
            'coverage' => 'array',
            'confidence' => 'float',
        ];
    }

    public function findings()
    {
        return $this->hasMany(AnalysisFinding::class, 'analysis_id');
    }
}
